# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78208c14f678ea311e17a7e152405b3b73d3ccd9da8b24e39767ef33b9c5c51b606035cb288ea1105aba4a475ea12f5f84dc66d69d8a3dbe676385d0331dba71

test:
  secret_key_base: 3e807b7e629639a49ee8e75ae11a63984d71843b6db236974aa451497bb298209aab7832ac2357c21d4d4e081196087980336ed32a463668903a2358ebee29ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
