User.create(username: "aaa")
User.create(username: "bbb")
User.create(username: "ccc")
User.create(username: "ddd")
User.create(username: "eee")
User.create(username: "fff")
User.create(username: "Wei")
User.create(username: "Peter")
Tweet.create(messages: "jojojojjojojojojo", user_id: "8")
Tweet.create(messages: "vhvhvhvhvhhvhvhvh", user_id: "1")
Tweet.create(messages: "jojojojjfyfyfyojo", user_id: "7")
Tweet.create(messages: "vvgvgvgvgjojojojo", user_id: "7")
Tweet.create(messages: "jovhvhvhvjojojojo", user_id: "7")
